// src/main/webapp/app/entities/child/child-detail.tsx
import React, { useEffect } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
import {} from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { useAppDispatch, useAppSelector } from 'app/config/store';

import { getEntity } from './child.reducer';

export const ChildDetail = () => {
  const dispatch = useAppDispatch();

  const { id } = useParams<'id'>();

  useEffect(() => {
    dispatch(getEntity(id));
  }, []);

  const childEntity = useAppSelector(state => state.child.entity);
  return (
    <Row>
      <Col md="8">
        <h2 data-cy="childDetailsHeading">Child</h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="id">ID</span>
          </dt>
          <dd>{childEntity.id}</dd>
          <dt>
            <span id="firstName">First Name</span>
          </dt>
          <dd>{childEntity.firstName}</dd>
          <dt>
            <span id="lastName">Last Name</span>
          </dt>
          <dd>{childEntity.lastName}</dd>
          <dt>
            <span id="gender">Gender</span>
          </dt>
          <dd>{childEntity.gender}</dd>
          <dt>
            <span id="age">Age</span>
          </dt>
          <dd>{childEntity.age}</dd>
          <dt>Learning</dt>
          <dd>{childEntity.learning ? childEntity.learning.id : ''}</dd>
          <dt>Parent</dt>
          <dd>{childEntity.parent ? childEntity.parent.id : ''}</dd>
        </dl>
        <Button tag={Link} to="/child" replace color="info" data-cy="entityDetailsBackButton">
          <FontAwesomeIcon icon="arrow-left" /> <span className="d-none d-md-inline">Back</span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/child/${childEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" /> <span className="d-none d-md-inline">Edit</span>
        </Button>
      </Col>
    </Row>
  );
};

export default ChildDetail;

// src/main/webapp/app/entities/child/detail/child-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { IChild } from '../child.model';

@Component({
  selector: 'jhi-child-detail',
  templateUrl: './child-detail.component.html',
})
export class ChildDetailComponent implements OnInit {
  child: IChild | null = null;

  constructor(protected activatedRoute: ActivatedRoute) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ child }) => {
      this.child = child;
    });
  }

  previousState(): void {
    window.history.back();
  }
}

<div class="d-flex justify-content-center">
  <div class="col-8">
    <div *ngIf="child">
      <h2 data-cy="childDetailsHeading"><span>Child</span></h2>

      <hr />

      <jhi-alert-error></jhi-alert-error>

      <jhi-alert></jhi-alert>

      <dl class="row-md jh-entity-details">
        <dt><span>ID</span></dt>
        <dd>
          <span>{{ child.id }}</span>
        </dd>
        <dt><span>First Name</span></dt>
        <dd>
          <span>{{ child.firstName }}</span>
        </dd>
        <dt><span>Last Name</span></dt>
        <dd>
          <span>{{ child.lastName }}</span>
        </dd>
        <dt><span>Gender</span></dt>
        <dd>
          <span>{{ child.gender }}</span>
        </dd>
        <dt><span>Age</span></dt>
        <dd>
          <span>{{ child.age }}</span>
        </dd>
        <dt><span>Parent</span></dt>
        <dd>
          <div *ngIf="child.parent">
            <a [routerLink]="['/parent', child.parent.id, 'view']">{{ child.parent.id }}</a>
          </div>
        </dd>
      </dl>

      <button type="submit" (click)="previousState()" class="btn btn-info" data-cy="entityDetailsBackButton">
        <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span>Back</span>
      </button>

      <button type="button" [routerLink]="['/child', child.id, 'edit']" class="btn btn-primary">
        <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span>Edit</span>
      </button>
    </div>
  </div>
</div>
