// src/main/webapp/app/entities/tile/list/tile.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Data, ParamMap, Router } from '@angular/router';
import { combineLatest, filter, Observable, switchMap, tap } from 'rxjs';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { ITile } from '../tile.model';
import { ASC, DESC, SORT, ITEM_DELETED_EVENT, DEFAULT_SORT_DATA } from 'app/config/navigation.constants';
import { EntityArrayResponseType, TileService } from '../service/tile.service';
import { TileDeleteDialogComponent } from '../delete/tile-delete-dialog.component';
import { DataUtils } from 'app/core/util/data-util.service';
import { SortService } from 'app/shared/sort/sort.service';

@Component({
  selector: 'jhi-tile',
  templateUrl: './tile.component.html',
})
export class TileComponent implements OnInit {
  tiles?: ITile[];
  isLoading = false;

  predicate = 'id';
  ascending = true;

  constructor(
    protected tileService: TileService,
    protected activatedRoute: ActivatedRoute,
    public router: Router,
    protected sortService: SortService,
    protected dataUtils: DataUtils,
    protected modalService: NgbModal
  ) {}

  trackId = (_index: number, item: ITile): number => this.tileService.getTileIdentifier(item);

  ngOnInit(): void {
    this.load();
  }

  byteSize(base64String: string): string {
    return this.dataUtils.byteSize(base64String);
  }

  openFile(base64String: string, contentType: string | null | undefined): void {
    return this.dataUtils.openFile(base64String, contentType);
  }

  delete(tile: ITile): void {
    const modalRef = this.modalService.open(TileDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.tile = tile;
    // unsubscribe not needed because closed completes on modal close
    modalRef.closed
      .pipe(
        filter(reason => reason === ITEM_DELETED_EVENT),
        switchMap(() => this.loadFromBackendWithRouteInformations())
      )
      .subscribe({
        next: (res: EntityArrayResponseType) => {
          this.onResponseSuccess(res);
        },
      });
  }

  load(): void {
    this.loadFromBackendWithRouteInformations().subscribe({
      next: (res: EntityArrayResponseType) => {
        this.onResponseSuccess(res);
      },
    });
  }

  navigateToWithComponentValues(): void {
    this.handleNavigation(this.predicate, this.ascending);
  }

  protected loadFromBackendWithRouteInformations(): Observable<EntityArrayResponseType> {
    return combineLatest([this.activatedRoute.queryParamMap, this.activatedRoute.data]).pipe(
      tap(([params, data]) => this.fillComponentAttributeFromRoute(params, data)),
      switchMap(() => this.queryBackend(this.predicate, this.ascending))
    );
  }

  protected fillComponentAttributeFromRoute(params: ParamMap, data: Data): void {
    const sort = (params.get(SORT) ?? data[DEFAULT_SORT_DATA]).split(',');
    this.predicate = sort[0];
    this.ascending = sort[1] === ASC;
  }

  protected onResponseSuccess(response: EntityArrayResponseType): void {
    const dataFromBody = this.fillComponentAttributesFromResponseBody(response.body);
    this.tiles = this.refineData(dataFromBody);
  }

  protected refineData(data: ITile[]): ITile[] {
    return data.sort(this.sortService.startSort(this.predicate, this.ascending ? 1 : -1));
  }

  protected fillComponentAttributesFromResponseBody(data: ITile[] | null): ITile[] {
    return data ?? [];
  }

  protected queryBackend(predicate?: string, ascending?: boolean): Observable<EntityArrayResponseType> {
    this.isLoading = true;
    const queryObject = {
      sort: this.getSortQueryParam(predicate, ascending),
    };
    return this.tileService.query(queryObject).pipe(tap(() => (this.isLoading = false)));
  }

  protected handleNavigation(predicate?: string, ascending?: boolean): void {
    const queryParamsObj = {
      sort: this.getSortQueryParam(predicate, ascending),
    };

    this.router.navigate(['./'], {
      relativeTo: this.activatedRoute,
      queryParams: queryParamsObj,
    });
  }

  protected getSortQueryParam(predicate = this.predicate, ascending = this.ascending): string[] {
    const ascendingQueryParam = ascending ? ASC : DESC;
    if (predicate === '') {
      return [];
    } else {
      return [predicate + ',' + ascendingQueryParam];
    }
  }
}

<div>
  <h2 id="page-heading" data-cy="TileHeading">
    <span>Tiles</span>

    <div class="d-flex justify-content-end">
      <button class="btn btn-info me-2" (click)="load()" [disabled]="isLoading">
        <fa-icon icon="sync" [spin]="isLoading"></fa-icon>
        <span>Refresh list</span>
      </button>

      <button
        id="jh-create-entity"
        data-cy="entityCreateButton"
        class="btn btn-primary jh-create-entity create-tile"
        [routerLink]="['/tile/new']"
      >
        <fa-icon icon="plus"></fa-icon>
        <span> Create a new Tile </span>
      </button>
    </div>
  </h2>

  <jhi-alert-error></jhi-alert-error>

  <jhi-alert></jhi-alert>

  <div class="alert alert-warning" id="no-result" *ngIf="tiles?.length === 0">
    <span>No Tiles found</span>
  </div>

  <div class="table-responsive table-entities" id="entities" *ngIf="tiles && tiles.length > 0">
    <table class="table table-striped" aria-describedby="page-heading">
      <thead>
        <tr jhiSort [(predicate)]="predicate" [(ascending)]="ascending" (sortChange)="navigateToWithComponentValues()">
          <th scope="col" jhiSortBy="id">
            <div class="d-flex">
              <span>ID</span>
              <fa-icon class="p-1" icon="sort"></fa-icon>
            </div>
          </th>
          <th scope="col" jhiSortBy="status">
            <div class="d-flex">
              <span>Status</span>
              <fa-icon class="p-1" icon="sort"></fa-icon>
            </div>
          </th>
          <th scope="col" jhiSortBy="image">
            <div class="d-flex">
              <span>Image</span>
              <fa-icon class="p-1" icon="sort"></fa-icon>
            </div>
          </th>
          <th scope="col" jhiSortBy="audio">
            <div class="d-flex">
              <span>Audio</span>
              <fa-icon class="p-1" icon="sort"></fa-icon>
            </div>
          </th>
          <th scope="col" jhiSortBy="languageTitle">
            <div class="d-flex">
              <span>Language Title</span>
              <fa-icon class="p-1" icon="sort"></fa-icon>
            </div>
          </th>
          <th scope="col" jhiSortBy="englishTitle">
            <div class="d-flex">
              <span>English Title</span>
              <fa-icon class="p-1" icon="sort"></fa-icon>
            </div>
          </th>
          <th scope="col" jhiSortBy="question.id">
            <div class="d-flex">
              <span>Question</span>
              <fa-icon class="p-1" icon="sort"></fa-icon>
            </div>
          </th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let tile of tiles; trackBy: trackId" data-cy="entityTable">
          <td>
            <a [routerLink]="['/tile', tile.id, 'view']">{{ tile.id }}</a>
          </td>
          <td>{{ tile.status }}</td>
          <td>
            <a *ngIf="tile.image" (click)="openFile(tile.image, tile.imageContentType)">
              <img [src]="'data:' + tile.imageContentType + ';base64,' + tile.image" style="max-height: 30px" alt="tile image" />
            </a>
            <span *ngIf="tile.image">{{ tile.imageContentType }}, {{ byteSize(tile.image) }}</span>
          </td>
          <td>
            <a *ngIf="tile.audio" (click)="openFile(tile.audio, tile.audioContentType)">Open</a>
            <span *ngIf="tile.audio">{{ tile.audioContentType }}, {{ byteSize(tile.audio) }}</span>
          </td>
          <td>{{ tile.languageTitle }}</td>
          <td>{{ tile.englishTitle }}</td>
          <td>
            <div *ngIf="tile.question">
              <a [routerLink]="['/question', tile.question.id, 'view']">{{ tile.question.id }}</a>
            </div>
          </td>
          <td class="text-end">
            <div class="btn-group">
              <button type="submit" [routerLink]="['/tile', tile.id, 'view']" class="btn btn-info btn-sm" data-cy="entityDetailsButton">
                <fa-icon icon="eye"></fa-icon>
                <span class="d-none d-md-inline">View</span>
              </button>

              <button type="submit" [routerLink]="['/tile', tile.id, 'edit']" class="btn btn-primary btn-sm" data-cy="entityEditButton">
                <fa-icon icon="pencil-alt"></fa-icon>
                <span class="d-none d-md-inline">Edit</span>
              </button>

              <button type="submit" (click)="delete(tile)" class="btn btn-danger btn-sm" data-cy="entityDeleteButton">
                <fa-icon icon="times"></fa-icon>
                <span class="d-none d-md-inline">Delete</span>
              </button>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

// src/main/webapp/app/entities/tile/tile.tsx
import React, { useState, useEffect } from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { Button, Table } from 'reactstrap';
import { openFile, byteSize, Translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { useAppDispatch, useAppSelector } from 'app/config/store';

import { ITile } from 'app/shared/model/tile.model';
import { getEntities } from './tile.reducer';

export const Tile = () => {
  const dispatch = useAppDispatch();

  const location = useLocation();
  const navigate = useNavigate();

  const tileList = useAppSelector(state => state.tile.entities);
  const loading = useAppSelector(state => state.tile.loading);

  useEffect(() => {
    dispatch(getEntities({}));
  }, []);

  const handleSyncList = () => {
    dispatch(getEntities({}));
  };

  return (
    <div>
      <h2 id="tile-heading" data-cy="TileHeading">
        Tiles
        <div className="d-flex justify-content-end">
          <Button className="me-2" color="info" onClick={handleSyncList} disabled={loading}>
            <FontAwesomeIcon icon="sync" spin={loading} /> Refresh list
          </Button>
          <Link to="/tile/new" className="btn btn-primary jh-create-entity" id="jh-create-entity" data-cy="entityCreateButton">
            <FontAwesomeIcon icon="plus" />
            &nbsp; Create a new Tile
          </Link>
        </div>
      </h2>
      <div className="table-responsive">
        {tileList && tileList.length > 0 ? (
          <Table responsive>
            <thead>
              <tr>
                <th>ID</th>
                <th>Status</th>
                <th>Image</th>
                <th>Audio</th>
                <th>Language Title</th>
                <th>English Title</th>
                <th>Question</th>
                <th>Lesson</th>
                <th />
              </tr>
            </thead>
            <tbody>
              {tileList.map((tile, i) => (
                <tr key={`entity-${i}`} data-cy="entityTable">
                  <td>
                    <Button tag={Link} to={`/tile/${tile.id}`} color="link" size="sm">
                      {tile.id}
                    </Button>
                  </td>
                  <td>{tile.status}</td>
                  <td>
                    {tile.image ? (
                      <div>
                        {tile.imageContentType ? (
                          <a onClick={openFile(tile.imageContentType, tile.image)}>
                            <img src={`data:${tile.imageContentType};base64,${tile.image}`} style={{ maxHeight: '30px' }} />
                            &nbsp;
                          </a>
                        ) : null}
                        <span>
                          {tile.imageContentType}, {byteSize(tile.image)}
                        </span>
                      </div>
                    ) : null}
                  </td>
                  <td>
                    {tile.audio ? (
                      <div>
                        {tile.audioContentType ? <a onClick={openFile(tile.audioContentType, tile.audio)}>Open &nbsp;</a> : null}
                        <span>
                          {tile.audioContentType}, {byteSize(tile.audio)}
                        </span>
                      </div>
                    ) : null}
                  </td>
                  <td>{tile.languageTitle}</td>
                  <td>{tile.englishTitle}</td>
                  <td>{tile.question ? <Link to={`/question/${tile.question.id}`}>{tile.question.id}</Link> : ''}</td>
                  <td>{tile.lesson ? <Link to={`/lesson/${tile.lesson.id}`}>{tile.lesson.id}</Link> : ''}</td>
                  <td className="text-end">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`/tile/${tile.id}`} color="info" size="sm" data-cy="entityDetailsButton">
                        <FontAwesomeIcon icon="eye" /> <span className="d-none d-md-inline">View</span>
                      </Button>
                      <Button tag={Link} to={`/tile/${tile.id}/edit`} color="primary" size="sm" data-cy="entityEditButton">
                        <FontAwesomeIcon icon="pencil-alt" /> <span className="d-none d-md-inline">Edit</span>
                      </Button>
                      <Button tag={Link} to={`/tile/${tile.id}/delete`} color="danger" size="sm" data-cy="entityDeleteButton">
                        <FontAwesomeIcon icon="trash" /> <span className="d-none d-md-inline">Delete</span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        ) : (
          !loading && <div className="alert alert-warning">No Tiles found</div>
        )}
      </div>
    </div>
  );
};

export default Tile;
