// src/main/webapp/app/entities/multiple-choice/detail/multiple-choice-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { IMultipleChoice } from '../multiple-choice.model';
import { DataUtils } from 'app/core/util/data-util.service';

@Component({
  selector: 'jhi-multiple-choice-detail',
  templateUrl: './multiple-choice-detail.component.html',
})
export class MultipleChoiceDetailComponent implements OnInit {
  multipleChoice: IMultipleChoice | null = null;

  constructor(protected dataUtils: DataUtils, protected activatedRoute: ActivatedRoute) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ multipleChoice }) => {
      this.multipleChoice = multipleChoice;
    });
  }

  byteSize(base64String: string): string {
    return this.dataUtils.byteSize(base64String);
  }

  openFile(base64String: string, contentType: string | null | undefined): void {
    this.dataUtils.openFile(base64String, contentType);
  }

  previousState(): void {
    window.history.back();
  }
}

<div class="d-flex justify-content-center">
  <div class="col-8">
    <div *ngIf="multipleChoice">
      <h2 data-cy="multipleChoiceDetailsHeading"><span>Multiple Choice</span></h2>

      <hr />

      <jhi-alert-error></jhi-alert-error>

      <jhi-alert></jhi-alert>

      <dl class="row-md jh-entity-details">
        <dt><span>ID</span></dt>
        <dd>
          <span>{{ multipleChoice.id }}</span>
        </dd>
        <dt><span>Status</span></dt>
        <dd>
          <span>{{ multipleChoice.status }}</span>
        </dd>
        <dt><span>Image</span></dt>
        <dd>
          <div *ngIf="multipleChoice.image">
            <a (click)="openFile(multipleChoice.image, multipleChoice.imageContentType)">
              <img
                [src]="'data:' + multipleChoice.imageContentType + ';base64,' + multipleChoice.image"
                style="max-width: 100%"
                alt="multipleChoice image"
              />
            </a>
            {{ multipleChoice.imageContentType }}, {{ byteSize(multipleChoice.image) }}
          </div>
        </dd>
        <dt><span>Question</span></dt>
        <dd>
          <div *ngIf="multipleChoice.question">
            <a [routerLink]="['/question', multipleChoice.question.id, 'view']">{{ multipleChoice.question.id }}</a>
          </div>
        </dd>
      </dl>

      <button type="submit" (click)="previousState()" class="btn btn-info" data-cy="entityDetailsBackButton">
        <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span>Back</span>
      </button>

      <button type="button" [routerLink]="['/multiple-choice', multipleChoice.id, 'edit']" class="btn btn-primary">
        <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span>Edit</span>
      </button>
    </div>
  </div>
</div>

// src/main/webapp/app/entities/multiple-choice/multiple-choice-detail.tsx
import React, { useEffect } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
import { openFile, byteSize } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { useAppDispatch, useAppSelector } from 'app/config/store';

import { getEntity } from './multiple-choice.reducer';

export const MultipleChoiceDetail = () => {
  const dispatch = useAppDispatch();

  const { id } = useParams<'id'>();

  useEffect(() => {
    dispatch(getEntity(id));
  }, []);

  const multipleChoiceEntity = useAppSelector(state => state.multipleChoice.entity);
  return (
    <Row>
      <Col md="8">
        <h2 data-cy="multipleChoiceDetailsHeading">Multiple Choice</h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="id">ID</span>
          </dt>
          <dd>{multipleChoiceEntity.id}</dd>
          <dt>
            <span id="status">Status</span>
          </dt>
          <dd>{multipleChoiceEntity.status}</dd>
          <dt>
            <span id="image">Image</span>
          </dt>
          <dd>
            {multipleChoiceEntity.image ? (
              <div>
                {multipleChoiceEntity.imageContentType ? (
                  <a onClick={openFile(multipleChoiceEntity.imageContentType, multipleChoiceEntity.image)}>
                    <img
                      src={`data:${multipleChoiceEntity.imageContentType};base64,${multipleChoiceEntity.image}`}
                      style={{ maxHeight: '30px' }}
                    />
                  </a>
                ) : null}
                <span>
                  {multipleChoiceEntity.imageContentType}, {byteSize(multipleChoiceEntity.image)}
                </span>
              </div>
            ) : null}
          </dd>
          <dt>Question</dt>
          <dd>{multipleChoiceEntity.question ? multipleChoiceEntity.question.id : ''}</dd>
        </dl>
        <Button tag={Link} to="/multiple-choice" replace color="info" data-cy="entityDetailsBackButton">
          <FontAwesomeIcon icon="arrow-left" /> <span className="d-none d-md-inline">Back</span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/multiple-choice/${multipleChoiceEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" /> <span className="d-none d-md-inline">Edit</span>
        </Button>
      </Col>
    </Row>
  );
};

export default MultipleChoiceDetail;
