// src/main/webapp/app/entities/tile/tile-detail.tsx
import React, { useEffect } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
import { openFile, byteSize } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { useAppDispatch, useAppSelector } from 'app/config/store';

import { getEntity } from './tile.reducer';

export const TileDetail = () => {
  const dispatch = useAppDispatch();

  const { id } = useParams<'id'>();

  useEffect(() => {
    dispatch(getEntity(id));
  }, []);

  const tileEntity = useAppSelector(state => state.tile.entity);
  return (
    <Row>
      <Col md="8">
        <h2 data-cy="tileDetailsHeading">Tile</h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="id">ID</span>
          </dt>
          <dd>{tileEntity.id}</dd>
          <dt>
            <span id="status">Status</span>
          </dt>
          <dd>{tileEntity.status}</dd>
          <dt>
            <span id="image">Image</span>
          </dt>
          <dd>
            {tileEntity.image ? (
              <div>
                {tileEntity.imageContentType ? (
                  <a onClick={openFile(tileEntity.imageContentType, tileEntity.image)}>
                    <img src={`data:${tileEntity.imageContentType};base64,${tileEntity.image}`} style={{ maxHeight: '30px' }} />
                  </a>
                ) : null}
                <span>
                  {tileEntity.imageContentType}, {byteSize(tileEntity.image)}
                </span>
              </div>
            ) : null}
          </dd>
          <dt>
            <span id="audio">Audio</span>
          </dt>
          <dd>
            {tileEntity.audio ? (
              <div>
                {tileEntity.audioContentType ? <a onClick={openFile(tileEntity.audioContentType, tileEntity.audio)}>Open&nbsp;</a> : null}
                <span>
                  {tileEntity.audioContentType}, {byteSize(tileEntity.audio)}
                </span>
              </div>
            ) : null}
          </dd>
          <dt>
            <span id="languageTitle">Language Title</span>
          </dt>
          <dd>{tileEntity.languageTitle}</dd>
          <dt>
            <span id="englishTitle">English Title</span>
          </dt>
          <dd>{tileEntity.englishTitle}</dd>
          <dt>Question</dt>
          <dd>{tileEntity.question ? tileEntity.question.id : ''}</dd>
          <dt>Lesson</dt>
          <dd>{tileEntity.lesson ? tileEntity.lesson.id : ''}</dd>
        </dl>
        <Button tag={Link} to="/tile" replace color="info" data-cy="entityDetailsBackButton">
          <FontAwesomeIcon icon="arrow-left" /> <span className="d-none d-md-inline">Back</span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/tile/${tileEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" /> <span className="d-none d-md-inline">Edit</span>
        </Button>
      </Col>
    </Row>
  );
};

export default TileDetail;

// src/main/webapp/app/entities/tile/detail/tile-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { ITile } from '../tile.model';
import { DataUtils } from 'app/core/util/data-util.service';

@Component({
  selector: 'jhi-tile-detail',
  templateUrl: './tile-detail.component.html',
})
export class TileDetailComponent implements OnInit {
  tile: ITile | null = null;

  constructor(protected dataUtils: DataUtils, protected activatedRoute: ActivatedRoute) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ tile }) => {
      this.tile = tile;
    });
  }

  byteSize(base64String: string): string {
    return this.dataUtils.byteSize(base64String);
  }

  openFile(base64String: string, contentType: string | null | undefined): void {
    this.dataUtils.openFile(base64String, contentType);
  }

  previousState(): void {
    window.history.back();
  }
}

<div class="d-flex justify-content-center">
  <div class="col-8">
    <div *ngIf="tile">
      <h2 data-cy="tileDetailsHeading"><span>Tile</span></h2>

      <hr />

      <jhi-alert-error></jhi-alert-error>

      <jhi-alert></jhi-alert>

      <dl class="row-md jh-entity-details">
        <dt><span>ID</span></dt>
        <dd>
          <span>{{ tile.id }}</span>
        </dd>
        <dt><span>Status</span></dt>
        <dd>
          <span>{{ tile.status }}</span>
        </dd>
        <dt><span>Image</span></dt>
        <dd>
          <div *ngIf="tile.image">
            <a (click)="openFile(tile.image, tile.imageContentType)">
              <img [src]="'data:' + tile.imageContentType + ';base64,' + tile.image" style="max-width: 100%" alt="tile image" />
            </a>
            {{ tile.imageContentType }}, {{ byteSize(tile.image) }}
          </div>
        </dd>
        <dt><span>Audio</span></dt>
        <dd>
          <div *ngIf="tile.audio">
            <a (click)="openFile(tile.audio, tile.audioContentType)">Open</a>
            {{ tile.audioContentType }}, {{ byteSize(tile.audio) }}
          </div>
        </dd>
        <dt><span>Language Title</span></dt>
        <dd>
          <span>{{ tile.languageTitle }}</span>
        </dd>
        <dt><span>English Title</span></dt>
        <dd>
          <span>{{ tile.englishTitle }}</span>
        </dd>
        <dt><span>Question</span></dt>
        <dd>
          <div *ngIf="tile.question">
            <a [routerLink]="['/question', tile.question.id, 'view']">{{ tile.question.id }}</a>
          </div>
        </dd>
      </dl>

      <button type="submit" (click)="previousState()" class="btn btn-info" data-cy="entityDetailsBackButton">
        <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span>Back</span>
      </button>

      <button type="button" [routerLink]="['/tile', tile.id, 'edit']" class="btn btn-primary">
        <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span>Edit</span>
      </button>
    </div>
  </div>
</div>
