// src/main/webapp/app/entities/question/question-detail.tsx
import React, { useEffect } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
import { openFile, byteSize } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { useAppDispatch, useAppSelector } from 'app/config/store';

import { getEntity } from './question.reducer';

export const QuestionDetail = () => {
  const dispatch = useAppDispatch();

  const { id } = useParams<'id'>();

  useEffect(() => {
    dispatch(getEntity(id));
  }, []);

  const questionEntity = useAppSelector(state => state.question.entity);
  return (
    <Row>
      <Col md="8">
        <h2 data-cy="questionDetailsHeading">Question</h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="id">ID</span>
          </dt>
          <dd>{questionEntity.id}</dd>
          <dt>
            <span id="description">Description</span>
          </dt>
          <dd>{questionEntity.description}</dd>
          <dt>
            <span id="audio">Audio</span>
          </dt>
          <dd>
            {questionEntity.audio ? (
              <div>
                {questionEntity.audioContentType ? (
                  <a onClick={openFile(questionEntity.audioContentType, questionEntity.audio)}>Open&nbsp;</a>
                ) : null}
                <span>
                  {questionEntity.audioContentType}, {byteSize(questionEntity.audio)}
                </span>
              </div>
            ) : null}
          </dd>
          <dt>
            <span id="audioDescription">Audio Description</span>
          </dt>
          <dd>{questionEntity.audioDescription}</dd>
        </dl>
        <Button tag={Link} to="/question" replace color="info" data-cy="entityDetailsBackButton">
          <FontAwesomeIcon icon="arrow-left" /> <span className="d-none d-md-inline">Back</span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/question/${questionEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" /> <span className="d-none d-md-inline">Edit</span>
        </Button>
      </Col>
    </Row>
  );
};

export default QuestionDetail;

// src/main/webapp/app/entities/question/detail/question-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { IQuestion } from '../question.model';
import { DataUtils } from 'app/core/util/data-util.service';

@Component({
  selector: 'jhi-question-detail',
  templateUrl: './question-detail.component.html',
})
export class QuestionDetailComponent implements OnInit {
  question: IQuestion | null = null;

  constructor(protected dataUtils: DataUtils, protected activatedRoute: ActivatedRoute) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ question }) => {
      this.question = question;
    });
  }

  byteSize(base64String: string): string {
    return this.dataUtils.byteSize(base64String);
  }

  openFile(base64String: string, contentType: string | null | undefined): void {
    this.dataUtils.openFile(base64String, contentType);
  }

  previousState(): void {
    window.history.back();
  }
}

<div class="d-flex justify-content-center">
  <div class="col-8">
    <div *ngIf="question">
      <h2 data-cy="questionDetailsHeading"><span>Question</span></h2>

      <hr />

      <jhi-alert-error></jhi-alert-error>

      <jhi-alert></jhi-alert>

      <dl class="row-md jh-entity-details">
        <dt><span>ID</span></dt>
        <dd>
          <span>{{ question.id }}</span>
        </dd>
        <dt><span>Description</span></dt>
        <dd>
          <span>{{ question.description }}</span>
        </dd>
        <dt><span>Audio</span></dt>
        <dd>
          <div *ngIf="question.audio">
            <a (click)="openFile(question.audio, question.audioContentType)">Open</a>
            {{ question.audioContentType }}, {{ byteSize(question.audio) }}
          </div>
        </dd>
        <dt><span>Audio Description</span></dt>
        <dd>
          <span>{{ question.audioDescription }}</span>
        </dd>
      </dl>

      <button type="submit" (click)="previousState()" class="btn btn-info" data-cy="entityDetailsBackButton">
        <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span>Back</span>
      </button>

      <button type="button" [routerLink]="['/question', question.id, 'edit']" class="btn btn-primary">
        <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span>Edit</span>
      </button>
    </div>
  </div>
</div>
