// src/main/webapp/app/entities/learning/update/learning-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { finalize } from 'rxjs/operators';

import { LearningFormService, LearningFormGroup } from './learning-form.service';
import { ILearning } from '../learning.model';
import { LearningService } from '../service/learning.service';
import { Language } from 'app/entities/enumerations/language.model';

@Component({
  selector: 'jhi-learning-update',
  templateUrl: './learning-update.component.html',
})
export class LearningUpdateComponent implements OnInit {
  isSaving = false;
  learning: ILearning | null = null;
  languageValues = Object.keys(Language);

  editForm: LearningFormGroup = this.learningFormService.createLearningFormGroup();

  constructor(
    protected learningService: LearningService,
    protected learningFormService: LearningFormService,
    protected activatedRoute: ActivatedRoute
  ) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ learning }) => {
      this.learning = learning;
      if (learning) {
        this.updateForm(learning);
      }
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const learning = this.learningFormService.getLearning(this.editForm);
    if (learning.id !== null) {
      this.subscribeToSaveResponse(this.learningService.update(learning));
    } else {
      this.subscribeToSaveResponse(this.learningService.create(learning));
    }
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<ILearning>>): void {
    result.pipe(finalize(() => this.onSaveFinalize())).subscribe({
      next: () => this.onSaveSuccess(),
      error: () => this.onSaveError(),
    });
  }

  protected onSaveSuccess(): void {
    this.previousState();
  }

  protected onSaveError(): void {
    // Api for inheritance.
  }

  protected onSaveFinalize(): void {
    this.isSaving = false;
  }

  protected updateForm(learning: ILearning): void {
    this.learning = learning;
    this.learningFormService.resetForm(this.editForm, learning);
  }
}

<div class="d-flex justify-content-center">
  <div class="col-8">
    <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
      <h2 id="jhi-learning-heading" data-cy="LearningCreateUpdateHeading">Create or edit a Learning</h2>

      <div>
        <jhi-alert-error></jhi-alert-error>

        <div class="row mb-3" *ngIf="editForm.controls.id.value !== null">
          <label class="form-label" for="field_id">ID</label>
          <input type="number" class="form-control" name="id" id="field_id" data-cy="id" formControlName="id" [readonly]="true" />
        </div>

        <div class="row mb-3">
          <label class="form-label" for="field_startDate">Start Date</label>
          <div class="d-flex">
            <input
              id="field_startDate"
              data-cy="startDate"
              type="datetime-local"
              class="form-control"
              name="startDate"
              formControlName="startDate"
              placeholder="YYYY-MM-DD HH:mm"
            />
          </div>
          <div *ngIf="editForm.get('startDate')!.invalid && (editForm.get('startDate')!.dirty || editForm.get('startDate')!.touched)">
            <small class="form-text text-danger" *ngIf="editForm.get('startDate')?.errors?.required"> This field is required. </small>
            <small class="form-text text-danger" [hidden]="!editForm.get('startDate')?.errors?.datetimelocal">
              This field should be a date and time.
            </small>
          </div>
        </div>

        <div class="row mb-3">
          <label class="form-label" for="field_endDate">End Date</label>
          <div class="d-flex">
            <input
              id="field_endDate"
              data-cy="endDate"
              type="datetime-local"
              class="form-control"
              name="endDate"
              formControlName="endDate"
              placeholder="YYYY-MM-DD HH:mm"
            />
          </div>
        </div>

        <div class="row mb-3">
          <label class="form-label" for="field_language">Language</label>
          <select class="form-control" name="language" formControlName="language" id="field_language" data-cy="language">
            <option [ngValue]="null"></option>
            <option *ngFor="let language of languageValues" [value]="language">language</option>
          </select>
          <div *ngIf="editForm.get('language')!.invalid && (editForm.get('language')!.dirty || editForm.get('language')!.touched)">
            <small class="form-text text-danger" *ngIf="editForm.get('language')?.errors?.required"> This field is required. </small>
          </div>
        </div>
      </div>

      <div>
        <button type="button" id="cancel-save" data-cy="entityCreateCancelButton" class="btn btn-secondary" (click)="previousState()">
          <fa-icon icon="ban"></fa-icon>&nbsp;<span>Cancel</span>
        </button>

        <button
          type="submit"
          id="save-entity"
          data-cy="entityCreateSaveButton"
          [disabled]="editForm.invalid || isSaving"
          class="btn btn-primary"
        >
          <fa-icon icon="save"></fa-icon>&nbsp;<span>Save</span>
        </button>
      </div>
    </form>
  </div>
</div>

// src/main/webapp/app/entities/learning/learning-update.tsx
import React, { useState, useEffect } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { Button, Row, Col, FormText } from 'reactstrap';
import { isNumber, ValidatedField, ValidatedForm } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { convertDateTimeFromServer, convertDateTimeToServer, displayDefaultDateTime } from 'app/shared/util/date-utils';
import { mapIdList } from 'app/shared/util/entity-utils';
import { useAppDispatch, useAppSelector } from 'app/config/store';

import { IChild } from 'app/shared/model/child.model';
import { getEntities as getChildren } from 'app/entities/child/child.reducer';
import { ILearning } from 'app/shared/model/learning.model';
import { Language } from 'app/shared/model/enumerations/language.model';
import { getEntity, updateEntity, createEntity, reset } from './learning.reducer';

export const LearningUpdate = () => {
  const dispatch = useAppDispatch();

  const navigate = useNavigate();

  const { id } = useParams<'id'>();
  const isNew = id === undefined;

  const children = useAppSelector(state => state.child.entities);
  const learningEntity = useAppSelector(state => state.learning.entity);
  const loading = useAppSelector(state => state.learning.loading);
  const updating = useAppSelector(state => state.learning.updating);
  const updateSuccess = useAppSelector(state => state.learning.updateSuccess);
  const languageValues = Object.keys(Language);

  const handleClose = () => {
    navigate('/learning');
  };

  useEffect(() => {
    if (isNew) {
      dispatch(reset());
    } else {
      dispatch(getEntity(id));
    }

    dispatch(getChildren({}));
  }, []);

  useEffect(() => {
    if (updateSuccess) {
      handleClose();
    }
  }, [updateSuccess]);

  const saveEntity = values => {
    values.startDate = convertDateTimeToServer(values.startDate);
    values.endDate = convertDateTimeToServer(values.endDate);

    const entity = {
      ...learningEntity,
      ...values,
    };

    if (isNew) {
      dispatch(createEntity(entity));
    } else {
      dispatch(updateEntity(entity));
    }
  };

  const defaultValues = () =>
    isNew
      ? {
          startDate: displayDefaultDateTime(),
          endDate: displayDefaultDateTime(),
        }
      : {
          language: 'KIKUYU',
          ...learningEntity,
          startDate: convertDateTimeFromServer(learningEntity.startDate),
          endDate: convertDateTimeFromServer(learningEntity.endDate),
        };

  return (
    <div>
      <Row className="justify-content-center">
        <Col md="8">
          <h2 id="lokolingoApp.learning.home.createOrEditLabel" data-cy="LearningCreateUpdateHeading">
            Create or edit a Learning
          </h2>
        </Col>
      </Row>
      <Row className="justify-content-center">
        <Col md="8">
          {loading ? (
            <p>Loading...</p>
          ) : (
            <ValidatedForm defaultValues={defaultValues()} onSubmit={saveEntity}>
              {!isNew ? <ValidatedField name="id" required readOnly id="learning-id" label="ID" validate={{ required: true }} /> : null}
              <ValidatedField
                label="Start Date"
                id="learning-startDate"
                name="startDate"
                data-cy="startDate"
                type="datetime-local"
                placeholder="YYYY-MM-DD HH:mm"
                validate={{
                  required: { value: true, message: 'This field is required.' },
                }}
              />
              <ValidatedField
                label="End Date"
                id="learning-endDate"
                name="endDate"
                data-cy="endDate"
                type="datetime-local"
                placeholder="YYYY-MM-DD HH:mm"
              />
              <ValidatedField label="Language" id="learning-language" name="language" data-cy="language" type="select">
                {languageValues.map(language => (
                  <option value={language} key={language}>
                    {language}
                  </option>
                ))}
              </ValidatedField>
              <Button tag={Link} id="cancel-save" data-cy="entityCreateCancelButton" to="/learning" replace color="info">
                <FontAwesomeIcon icon="arrow-left" />
                &nbsp;
                <span className="d-none d-md-inline">Back</span>
              </Button>
              &nbsp;
              <Button color="primary" id="save-entity" data-cy="entityCreateSaveButton" type="submit" disabled={updating}>
                <FontAwesomeIcon icon="save" />
                &nbsp; Save
              </Button>
            </ValidatedForm>
          )}
        </Col>
      </Row>
    </div>
  );
};

export default LearningUpdate;
