// src/main/webapp/app/entities/multiple-choice/multiple-choice.tsx
import React, { useState, useEffect } from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { Button, Table } from 'reactstrap';
import { openFile, byteSize, Translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { useAppDispatch, useAppSelector } from 'app/config/store';

import { IMultipleChoice } from 'app/shared/model/multiple-choice.model';
import { getEntities } from './multiple-choice.reducer';

export const MultipleChoice = () => {
  const dispatch = useAppDispatch();

  const location = useLocation();
  const navigate = useNavigate();

  const multipleChoiceList = useAppSelector(state => state.multipleChoice.entities);
  const loading = useAppSelector(state => state.multipleChoice.loading);

  useEffect(() => {
    dispatch(getEntities({}));
  }, []);

  const handleSyncList = () => {
    dispatch(getEntities({}));
  };

  return (
    <div>
      <h2 id="multiple-choice-heading" data-cy="MultipleChoiceHeading">
        Multiple Choices
        <div className="d-flex justify-content-end">
          <Button className="me-2" color="info" onClick={handleSyncList} disabled={loading}>
            <FontAwesomeIcon icon="sync" spin={loading} /> Refresh list
          </Button>
          <Link to="/multiple-choice/new" className="btn btn-primary jh-create-entity" id="jh-create-entity" data-cy="entityCreateButton">
            <FontAwesomeIcon icon="plus" />
            &nbsp; Create a new Multiple Choice
          </Link>
        </div>
      </h2>
      <div className="table-responsive">
        {multipleChoiceList && multipleChoiceList.length > 0 ? (
          <Table responsive>
            <thead>
              <tr>
                <th>ID</th>
                <th>Status</th>
                <th>Image</th>
                <th>Question</th>
                <th />
              </tr>
            </thead>
            <tbody>
              {multipleChoiceList.map((multipleChoice, i) => (
                <tr key={`entity-${i}`} data-cy="entityTable">
                  <td>
                    <Button tag={Link} to={`/multiple-choice/${multipleChoice.id}`} color="link" size="sm">
                      {multipleChoice.id}
                    </Button>
                  </td>
                  <td>{multipleChoice.status}</td>
                  <td>
                    {multipleChoice.image ? (
                      <div>
                        {multipleChoice.imageContentType ? (
                          <a onClick={openFile(multipleChoice.imageContentType, multipleChoice.image)}>
                            <img
                              src={`data:${multipleChoice.imageContentType};base64,${multipleChoice.image}`}
                              style={{ maxHeight: '30px' }}
                            />
                            &nbsp;
                          </a>
                        ) : null}
                        <span>
                          {multipleChoice.imageContentType}, {byteSize(multipleChoice.image)}
                        </span>
                      </div>
                    ) : null}
                  </td>
                  <td>
                    {multipleChoice.question ? (
                      <Link to={`/question/${multipleChoice.question.id}`}>{multipleChoice.question.id}</Link>
                    ) : (
                      ''
                    )}
                  </td>
                  <td className="text-end">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`/multiple-choice/${multipleChoice.id}`} color="info" size="sm" data-cy="entityDetailsButton">
                        <FontAwesomeIcon icon="eye" /> <span className="d-none d-md-inline">View</span>
                      </Button>
                      <Button
                        tag={Link}
                        to={`/multiple-choice/${multipleChoice.id}/edit`}
                        color="primary"
                        size="sm"
                        data-cy="entityEditButton"
                      >
                        <FontAwesomeIcon icon="pencil-alt" /> <span className="d-none d-md-inline">Edit</span>
                      </Button>
                      <Button
                        tag={Link}
                        to={`/multiple-choice/${multipleChoice.id}/delete`}
                        color="danger"
                        size="sm"
                        data-cy="entityDeleteButton"
                      >
                        <FontAwesomeIcon icon="trash" /> <span className="d-none d-md-inline">Delete</span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        ) : (
          !loading && <div className="alert alert-warning">No Multiple Choices found</div>
        )}
      </div>
    </div>
  );
};

export default MultipleChoice;

// src/main/webapp/app/entities/multiple-choice/list/multiple-choice.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Data, ParamMap, Router } from '@angular/router';
import { combineLatest, filter, Observable, switchMap, tap } from 'rxjs';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { IMultipleChoice } from '../multiple-choice.model';
import { ASC, DESC, SORT, ITEM_DELETED_EVENT, DEFAULT_SORT_DATA } from 'app/config/navigation.constants';
import { EntityArrayResponseType, MultipleChoiceService } from '../service/multiple-choice.service';
import { MultipleChoiceDeleteDialogComponent } from '../delete/multiple-choice-delete-dialog.component';
import { DataUtils } from 'app/core/util/data-util.service';
import { SortService } from 'app/shared/sort/sort.service';

@Component({
  selector: 'jhi-multiple-choice',
  templateUrl: './multiple-choice.component.html',
})
export class MultipleChoiceComponent implements OnInit {
  multipleChoices?: IMultipleChoice[];
  isLoading = false;

  predicate = 'id';
  ascending = true;

  constructor(
    protected multipleChoiceService: MultipleChoiceService,
    protected activatedRoute: ActivatedRoute,
    public router: Router,
    protected sortService: SortService,
    protected dataUtils: DataUtils,
    protected modalService: NgbModal
  ) {}

  trackId = (_index: number, item: IMultipleChoice): number => this.multipleChoiceService.getMultipleChoiceIdentifier(item);

  ngOnInit(): void {
    this.load();
  }

  byteSize(base64String: string): string {
    return this.dataUtils.byteSize(base64String);
  }

  openFile(base64String: string, contentType: string | null | undefined): void {
    return this.dataUtils.openFile(base64String, contentType);
  }

  delete(multipleChoice: IMultipleChoice): void {
    const modalRef = this.modalService.open(MultipleChoiceDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.multipleChoice = multipleChoice;
    // unsubscribe not needed because closed completes on modal close
    modalRef.closed
      .pipe(
        filter(reason => reason === ITEM_DELETED_EVENT),
        switchMap(() => this.loadFromBackendWithRouteInformations())
      )
      .subscribe({
        next: (res: EntityArrayResponseType) => {
          this.onResponseSuccess(res);
        },
      });
  }

  load(): void {
    this.loadFromBackendWithRouteInformations().subscribe({
      next: (res: EntityArrayResponseType) => {
        this.onResponseSuccess(res);
      },
    });
  }

  navigateToWithComponentValues(): void {
    this.handleNavigation(this.predicate, this.ascending);
  }

  protected loadFromBackendWithRouteInformations(): Observable<EntityArrayResponseType> {
    return combineLatest([this.activatedRoute.queryParamMap, this.activatedRoute.data]).pipe(
      tap(([params, data]) => this.fillComponentAttributeFromRoute(params, data)),
      switchMap(() => this.queryBackend(this.predicate, this.ascending))
    );
  }

  protected fillComponentAttributeFromRoute(params: ParamMap, data: Data): void {
    const sort = (params.get(SORT) ?? data[DEFAULT_SORT_DATA]).split(',');
    this.predicate = sort[0];
    this.ascending = sort[1] === ASC;
  }

  protected onResponseSuccess(response: EntityArrayResponseType): void {
    const dataFromBody = this.fillComponentAttributesFromResponseBody(response.body);
    this.multipleChoices = this.refineData(dataFromBody);
  }

  protected refineData(data: IMultipleChoice[]): IMultipleChoice[] {
    return data.sort(this.sortService.startSort(this.predicate, this.ascending ? 1 : -1));
  }

  protected fillComponentAttributesFromResponseBody(data: IMultipleChoice[] | null): IMultipleChoice[] {
    return data ?? [];
  }

  protected queryBackend(predicate?: string, ascending?: boolean): Observable<EntityArrayResponseType> {
    this.isLoading = true;
    const queryObject = {
      sort: this.getSortQueryParam(predicate, ascending),
    };
    return this.multipleChoiceService.query(queryObject).pipe(tap(() => (this.isLoading = false)));
  }

  protected handleNavigation(predicate?: string, ascending?: boolean): void {
    const queryParamsObj = {
      sort: this.getSortQueryParam(predicate, ascending),
    };

    this.router.navigate(['./'], {
      relativeTo: this.activatedRoute,
      queryParams: queryParamsObj,
    });
  }

  protected getSortQueryParam(predicate = this.predicate, ascending = this.ascending): string[] {
    const ascendingQueryParam = ascending ? ASC : DESC;
    if (predicate === '') {
      return [];
    } else {
      return [predicate + ',' + ascendingQueryParam];
    }
  }
}

<div>
  <h2 id="page-heading" data-cy="MultipleChoiceHeading">
    <span>Multiple Choices</span>

    <div class="d-flex justify-content-end">
      <button class="btn btn-info me-2" (click)="load()" [disabled]="isLoading">
        <fa-icon icon="sync" [spin]="isLoading"></fa-icon>
        <span>Refresh list</span>
      </button>

      <button
        id="jh-create-entity"
        data-cy="entityCreateButton"
        class="btn btn-primary jh-create-entity create-multiple-choice"
        [routerLink]="['/multiple-choice/new']"
      >
        <fa-icon icon="plus"></fa-icon>
        <span> Create a new Multiple Choice </span>
      </button>
    </div>
  </h2>

  <jhi-alert-error></jhi-alert-error>

  <jhi-alert></jhi-alert>

  <div class="alert alert-warning" id="no-result" *ngIf="multipleChoices?.length === 0">
    <span>No Multiple Choices found</span>
  </div>

  <div class="table-responsive table-entities" id="entities" *ngIf="multipleChoices && multipleChoices.length > 0">
    <table class="table table-striped" aria-describedby="page-heading">
      <thead>
        <tr jhiSort [(predicate)]="predicate" [(ascending)]="ascending" (sortChange)="navigateToWithComponentValues()">
          <th scope="col" jhiSortBy="id">
            <div class="d-flex">
              <span>ID</span>
              <fa-icon class="p-1" icon="sort"></fa-icon>
            </div>
          </th>
          <th scope="col" jhiSortBy="status">
            <div class="d-flex">
              <span>Status</span>
              <fa-icon class="p-1" icon="sort"></fa-icon>
            </div>
          </th>
          <th scope="col" jhiSortBy="image">
            <div class="d-flex">
              <span>Image</span>
              <fa-icon class="p-1" icon="sort"></fa-icon>
            </div>
          </th>
          <th scope="col" jhiSortBy="question.id">
            <div class="d-flex">
              <span>Question</span>
              <fa-icon class="p-1" icon="sort"></fa-icon>
            </div>
          </th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let multipleChoice of multipleChoices; trackBy: trackId" data-cy="entityTable">
          <td>
            <a [routerLink]="['/multiple-choice', multipleChoice.id, 'view']">{{ multipleChoice.id }}</a>
          </td>
          <td>{{ multipleChoice.status }}</td>
          <td>
            <a *ngIf="multipleChoice.image" (click)="openFile(multipleChoice.image, multipleChoice.imageContentType)">
              <img
                [src]="'data:' + multipleChoice.imageContentType + ';base64,' + multipleChoice.image"
                style="max-height: 30px"
                alt="multipleChoice image"
              />
            </a>
            <span *ngIf="multipleChoice.image">{{ multipleChoice.imageContentType }}, {{ byteSize(multipleChoice.image) }}</span>
          </td>
          <td>
            <div *ngIf="multipleChoice.question">
              <a [routerLink]="['/question', multipleChoice.question.id, 'view']">{{ multipleChoice.question.id }}</a>
            </div>
          </td>
          <td class="text-end">
            <div class="btn-group">
              <button
                type="submit"
                [routerLink]="['/multiple-choice', multipleChoice.id, 'view']"
                class="btn btn-info btn-sm"
                data-cy="entityDetailsButton"
              >
                <fa-icon icon="eye"></fa-icon>
                <span class="d-none d-md-inline">View</span>
              </button>

              <button
                type="submit"
                [routerLink]="['/multiple-choice', multipleChoice.id, 'edit']"
                class="btn btn-primary btn-sm"
                data-cy="entityEditButton"
              >
                <fa-icon icon="pencil-alt"></fa-icon>
                <span class="d-none d-md-inline">Edit</span>
              </button>

              <button type="submit" (click)="delete(multipleChoice)" class="btn btn-danger btn-sm" data-cy="entityDeleteButton">
                <fa-icon icon="times"></fa-icon>
                <span class="d-none d-md-inline">Delete</span>
              </button>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
