// src/main/webapp/app/entities/multiple-choice/multiple-choice-delete-dialog.tsx
import React, { useEffect, useState } from 'react';
import { useLocation, useNavigate, useParams } from 'react-router-dom';
import { Modal, ModalHeader, ModalBody, ModalFooter, Button } from 'reactstrap';

import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { useAppDispatch, useAppSelector } from 'app/config/store';
import { getEntity, deleteEntity } from './multiple-choice.reducer';

export const MultipleChoiceDeleteDialog = () => {
  const dispatch = useAppDispatch();

  const location = useLocation();
  const navigate = useNavigate();
  const { id } = useParams<'id'>();

  const [loadModal, setLoadModal] = useState(false);

  useEffect(() => {
    dispatch(getEntity(id));
    setLoadModal(true);
  }, []);

  const multipleChoiceEntity = useAppSelector(state => state.multipleChoice.entity);
  const updateSuccess = useAppSelector(state => state.multipleChoice.updateSuccess);

  const handleClose = () => {
    navigate('/multiple-choice');
  };

  useEffect(() => {
    if (updateSuccess && loadModal) {
      handleClose();
      setLoadModal(false);
    }
  }, [updateSuccess]);

  const confirmDelete = () => {
    dispatch(deleteEntity(multipleChoiceEntity.id));
  };

  return (
    <Modal isOpen toggle={handleClose}>
      <ModalHeader toggle={handleClose} data-cy="multipleChoiceDeleteDialogHeading">
        Confirm delete operation
      </ModalHeader>
      <ModalBody id="lokolingoApp.multipleChoice.delete.question">
        Are you sure you want to delete Multiple Choice {multipleChoiceEntity.id}?
      </ModalBody>
      <ModalFooter>
        <Button color="secondary" onClick={handleClose}>
          <FontAwesomeIcon icon="ban" />
          &nbsp; Cancel
        </Button>
        <Button id="jhi-confirm-delete-multipleChoice" data-cy="entityConfirmDeleteButton" color="danger" onClick={confirmDelete}>
          <FontAwesomeIcon icon="trash" />
          &nbsp; Delete
        </Button>
      </ModalFooter>
    </Modal>
  );
};

export default MultipleChoiceDeleteDialog;

// src/main/webapp/app/entities/multiple-choice/delete/multiple-choice-delete-dialog.component.ts
import { Component } from '@angular/core';
import { NgbActiveModal } from '@ng-bootstrap/ng-bootstrap';

import { IMultipleChoice } from '../multiple-choice.model';
import { MultipleChoiceService } from '../service/multiple-choice.service';
import { ITEM_DELETED_EVENT } from 'app/config/navigation.constants';

@Component({
  templateUrl: './multiple-choice-delete-dialog.component.html',
})
export class MultipleChoiceDeleteDialogComponent {
  multipleChoice?: IMultipleChoice;

  constructor(protected multipleChoiceService: MultipleChoiceService, protected activeModal: NgbActiveModal) {}

  cancel(): void {
    this.activeModal.dismiss();
  }

  confirmDelete(id: number): void {
    this.multipleChoiceService.delete(id).subscribe(() => {
      this.activeModal.close(ITEM_DELETED_EVENT);
    });
  }
}

<form *ngIf="multipleChoice" name="deleteForm" (ngSubmit)="confirmDelete(multipleChoice.id!)">
  <div class="modal-header">
    <h4 class="modal-title" data-cy="multipleChoiceDeleteDialogHeading">Confirm delete operation</h4>

    <button type="button" class="btn-close" data-dismiss="modal" aria-hidden="true" (click)="cancel()">&times;</button>
  </div>

  <div class="modal-body">
    <jhi-alert-error></jhi-alert-error>
    <p id="jhi-delete-multipleChoice-heading">Are you sure you want to delete Multiple Choice {{ multipleChoice.id }}?</p>
  </div>

  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal" (click)="cancel()">
      <fa-icon icon="ban"></fa-icon>&nbsp;<span>Cancel</span>
    </button>

    <button id="jhi-confirm-delete-multipleChoice" data-cy="entityConfirmDeleteButton" type="submit" class="btn btn-danger">
      <fa-icon icon="times"></fa-icon>&nbsp;<span>Delete</span>
    </button>
  </div>
</form>
